name: Fetch Votes

on:
  push:
    branches:
      - action/fetch-votes
  # schedule:
    # - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Create Folder
        run: mkdir -p output/votes

      - name: Execute CLI fetchVotes
        run: go run presenter/cli/main.go fetchVotes

      - name: Commit output file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "fetc votes - $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git push
